version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-broker
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1
    environment:
      CELERY_BROKER_URL: redis://redis-broker:6379/0
      CELERY_RESULT_BACKEND: redis://redis-broker:6379/0

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/cmokashi/Documents/GitHub/neuroanalyst/outputs/redis/
      o: bind