"""
Module working with NeuProcessLogic.

Purpose-
- To create a structure around a piece of code that can then be wrapped around by a NeuProcess structure.
- The NeuProcess can then be wrapped around by NeuProcessExec which would be used in NeuPipeline.
"""
from ...about import About
from ....utils.constants import NeuroAnalystPaths

from pathlib import Path
from typing import Self, Optional, Any
from enum import Enum
from importlib.resources import files
import shutil
import json, yaml

from pydantic import BaseModel, Field, field_validator, model_validator

# =======================Default Logic=======================

DEFAULT_ARGS_DICT: list[dict] = [
    {
        "name": "input_filepath",
        "type": "str | PosixPath",
        "description": "Path to the input file"
    }
]

# =======================Allowed Keys=======================

try:
    with files("bids").joinpath("layout", "config", "derivatives.json").open("r") as f:
        derivatives_config = json.load(f)
except Exception as e:
    derivatives_config = {}
    print(f"Error loading derivatives config: {e}")
try:
    with files("bids").joinpath("layout", "config", "bids.json").open("r") as f:
        bids_config = json.load(f)
except Exception as e:
    bids_config = {}
    print(f"Error loading BIDS config: {e}")
    
ALLOWED_PYBIDS_ENTITY_KEYS = []    
for config in [bids_config, derivatives_config]:
    if "entities" in config:
        if isinstance(config["entities"], list) and config["entities"]:
            if not "name" in config["entities"][0]:
                print("Warning: 'name' key not found in entities")
                continue
            for entity in config["entities"]:
                ALLOWED_PYBIDS_ENTITY_KEYS.append(entity["name"])

if ALLOWED_PYBIDS_ENTITY_KEYS:
    ALLOWED_PYBIDS_ENTITY_KEYS = list(set(ALLOWED_PYBIDS_ENTITY_KEYS))  # Remove duplicates if any
else:
    ALLOWED_PYBIDS_ENTITY_KEYS = [
        "subject", "session", "extension", "suffix", "datatype"
    ]
    
# Remove 'subject' and 'session' from allowed keys as it's always handled separately
forbidden_keys = ["subject", "session", "scope"]
for key in forbidden_keys:
    if key in ALLOWED_PYBIDS_ENTITY_KEYS:
        ALLOWED_PYBIDS_ENTITY_KEYS.remove(key)

# ==================================================

class Metric(BaseModel):
    """Represents a quantitative metric derived from data"""
    value: Any
    name: str
    unit: Optional[str] = None
    description: str = ""
    category: Optional[str] = None
    labels: Optional[list[str]] = None
    
    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, Metric):
            return False
        return (
            self.value == other.value and
            self.name == other.name and
            self.unit == other.unit and
            self.description == other.description and
            self.category == other.category and 
            self.labels == other.labels
        )
        
    def __ne__(self, other: Any) -> bool:
        return not self.__eq__(other)

class ProgrammingLanguage(str, Enum):
    PYTHON = "python"
    MATLAB = "matlab"
    JAVASCRIPT = "javascript"
    JAVA = "java"
    C_SHARP = "csharp"
    RUBY = "ruby"

class NeuProcessKind(str, Enum):
    FILE = "file"  # Operates on individual files
    BULK = "bulk"  # Operates on the entire dataset at once

class NeuProcessLogicArgument(BaseModel):
    name: str = Field(..., description="Name of the argument")
    type: str = Field(..., description="Type of the argument")
    is_optional: bool = Field(False, description="Whether the argument is optional")
    description: str = Field(..., description="Description of the argument")

class NeuProcessLogic(BaseModel):
    username: Optional[str] = Field(default=None, description="Username of the user registering the process logic")
    about: About = Field(..., description="About the process logic")
    language: ProgrammingLanguage = Field(default=ProgrammingLanguage.PYTHON, description="Programming language used in the process logic")
    kind: NeuProcessKind = Field(default=NeuProcessKind.FILE, description="Kind of processing - file-level or bulk dataset processing")
    code: str = Field(..., description="Code for the process logic")
    import_statements: list[str] = Field(
        default_factory=list, description="List of import statements required for the process logic"
    )
    arguments: list[NeuProcessLogicArgument] = Field(
        default_factory=list, description="List of arguments for the process logic"
    )
    install_commands: str = Field(default='', description="Custom install commands for the process logic (semicolon & space separated)")
    output_entities: dict[str, str] = Field(
        default_factory=dict, description="Dictionary of output entities generated by the process logic (only for Python)",
        frozen=True
    )
    has_metrics: bool = Field(
        default=False, description="Indicates if a 'metrics' dictionary is available in the code (only for Python)"
    )
    
    def __str__(self) -> str:
        """Return a human-readable string representation of the NeuProcessLogic."""
        return f"NeuProcessLogic(name='{self.about.name}', language={self.language}, kind={self.kind})"
    
    def __repr__(self) -> str:
        """Return a detailed string representation of the NeuProcessLogic."""
        code_preview = self.code[:50] + '...' if len(self.code) > 50 else self.code
        args = [arg.name for arg in self.arguments]
        imports = len(self.import_statements)
        
        return f"NeuProcessLogic(name='{self.about.name}', "\
               f"language={self.language}, kind={self.kind}, "\
               f"arguments={args}, imports={imports}, "\
               f"code='{code_preview}')"


    @field_validator("arguments")
    def validate_arguments(cls, v, info):
        # Get the kind from the validation info data
        kind = info.data.get("kind", NeuProcessKind.FILE)
        
        # Set default arguments if empty list, based on processing kind
        if not v:
            if kind == NeuProcessKind.BULK:
                # Bulk processing doesn't require specific arguments by default
                # The user's function should handle dataset access directly
                v = []
            else:
                # File-level processing requires input_filepath argument
                v = [NeuProcessLogicArgument(**arg) for arg in DEFAULT_ARGS_DICT]
        return v
        
    @field_validator("output_entities")
    def validate_output_entities(cls, v):
        if not v:
            return v
            
        # Check 1: All values must be strings (no nesting)
        for key, value in v.items():
            if not isinstance(value, str):
                raise ValueError(f"Value for key '{key}' must be a string, got {type(value).__name__}")
            
        # Check 2: Values should not have spaces, commas, underscores, hyphens, or special characters
        for key, value in v.items():
            if any(char in value for char in [' ', ',', '_', '-', '/', '\\', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')']):
                raise ValueError(f"Value for key '{key}' contains invalid characters. Only alphanumeric characters are allowed.")
        
        # Check 3: All keys must be from the allowed set
        for key in v:
            if key not in ALLOWED_PYBIDS_ENTITY_KEYS:
                allowed_keys_str = ", ".join(f"'{k}'" for k in ALLOWED_PYBIDS_ENTITY_KEYS)
                raise ValueError(f"Invalid key '{key}'. Allowed keys are: {allowed_keys_str}")
                
        return v
    
    @classmethod
    def from_func_name(cls, func_name: str, username: Optional[str] = None) -> Self:
        paths = NeuroAnalystPaths(username=username)
        function_dir: Path = paths.get_function_workdir(func_name)
        if not function_dir.exists():
            raise FileNotFoundError(f"Function directory does not exist: {function_dir}")
        model_file = function_dir / "model.json"
        if not model_file.exists():
            raise FileNotFoundError(f"Model file does not exist: {model_file}")
        with model_file.open("r") as f:
            model_data = json.load(f)
        return cls.model_validate(model_data)
    
    @staticmethod
    def get_all_registered_logics(username: Optional[str] = None) -> list[Self]:
        """Get a list of all registered NeuProcessLogic instances."""
        paths = NeuroAnalystPaths(username=username)
        function_workdir = paths.functions
        if not function_workdir.exists():
            return []
        
        logics = []
        for item in function_workdir.iterdir():
            if item.is_dir():
                try:
                    logic = NeuProcessLogic.from_func_name(item.name, username=username)
                    logics.append(logic)
                except Exception as e:
                    print(f"Error loading logic from {item}: {e}")
        return logics
    
    def register(self, overwrite: bool = False) -> Path:
        """
        Register the NeuProcessLogic by saving its code and model to the functions directory.
        Returns the path to the function directory.
        
        Returns:
        Path: The path to the function directory.
        """
        
        paths = NeuroAnalystPaths(username=self.username)
        function_dir: Path = paths.get_function_workdir(self.about.name)
        if function_dir.exists() and not overwrite:
           raise FileExistsError(f"Function directory already exists: {function_dir} . Use a different function name or delete the existing directory, or set overwrite=True to overwrite.") 

        if function_dir.exists() and overwrite:
            shutil.rmtree(function_dir)

        function_dir.mkdir(parents=True, exist_ok=False)
        
        # Save the entire function (include imports) to a .py file
        function_file = function_dir / f"{self.about.name}.py"
        with function_file.open("w") as f:
            # Write import statements
            if self.import_statements:
                for imp in self.import_statements:
                    f.write(f"{imp}\n")
                f.write("\n\n")  # Add some space after imports
            
            # Write the main code
            f.write(self.code)
            
        # Save the model to a JSON file
        model = self.model_dump()
        model_file = function_dir / "model.json"
        with model_file.open("w") as f:
            json.dump(model, f, indent=4)
            
        return function_dir
    
    def delete(self):
        """
        Delete the NeuProcessLogic from the functions directory.
        """
        paths = NeuroAnalystPaths(username=self.username)
        function_dir: Path = paths.get_function_workdir(self.about.name)
        if not function_dir.exists():
            raise FileNotFoundError(f"Function directory does not exist: {function_dir}")
        shutil.rmtree(function_dir)