"""
Module working with NeuProcessLogic.

Purpose-
- To create a structure around a piece of code that can then be wrapped around by a NeuProcess structure.
- The NeuProcess can then be wrapped around by NeuProcessExec which would be used in NeuPipeline.
"""
from ...about import About

from enum import Enum
from importlib.resources import files
import json

from pydantic import BaseModel, Field, field_validator

# =======================Default Logic=======================

DEFAULT_ARGS_DICT: list[dict] = [
    {
        "name": "input_filepath",
        "type": "str | PosixPath",
        "description": "Path to the input file"
    }
]

# =======================Allowed Keys=======================

try:
    with files("bids").joinpath("layout", "config", "derivatives.json").open("r") as f:
        derivatives_config = json.load(f)
except Exception as e:
    derivatives_config = {}
    print(f"Error loading derivatives config: {e}")
try:
    with files("bids").joinpath("layout", "config", "bids.json").open("r") as f:
        bids_config = json.load(f)
except Exception as e:
    bids_config = {}
    print(f"Error loading BIDS config: {e}")
    
ALLOWED_PYBIDS_ENTITY_KEYS = []    
for config in [bids_config, derivatives_config]:
    if "entities" in config:
        if isinstance(config["entities"], list) and config["entities"]:
            if not "name" in config["entities"][0]:
                print("Warning: 'name' key not found in entities")
                continue
            for entity in config["entities"]:
                ALLOWED_PYBIDS_ENTITY_KEYS.append(entity["name"])

if ALLOWED_PYBIDS_ENTITY_KEYS:
    ALLOWED_PYBIDS_ENTITY_KEYS = list(set(ALLOWED_PYBIDS_ENTITY_KEYS))  # Remove duplicates if any
else:
    ALLOWED_PYBIDS_ENTITY_KEYS = [
        "subject", "session", "extension", "suffix", "datatype"
    ]
    
# Remove 'subject' and 'session' from allowed keys as it's always handled separately
forbidden_keys = ["subject", "session"]
for key in forbidden_keys:
    if key in ALLOWED_PYBIDS_ENTITY_KEYS:
        ALLOWED_PYBIDS_ENTITY_KEYS.remove(key)

# ==================================================

class ProgrammingLanguage(str, Enum):
    PYTHON = "python"
    MATLAB = "matlab"
    JAVASCRIPT = "javascript"
    JAVA = "java"
    C_SHARP = "csharp"
    RUBY = "ruby"

class NeuProcessKind(str, Enum):
    FILE = "file"  # Operates on individual files
    BULK = "bulk"  # Operates on the entire dataset at once

class NeuProcessLogicArgument(BaseModel):
    name: str = Field(..., description="Name of the argument")
    type: str = Field(..., description="Type of the argument")
    is_optional: bool = Field(False, description="Whether the argument is optional")
    description: str = Field(..., description="Description of the argument")

class NeuProcessLogic(BaseModel):
    about: About = Field(..., description="About the process logic")
    language: ProgrammingLanguage = Field(default=ProgrammingLanguage.PYTHON, description="Programming language used in the process logic")
    kind: NeuProcessKind = Field(default=NeuProcessKind.FILE, description="Kind of processing - file-level or bulk dataset processing")
    code: str = Field(..., description="Code for the process logic")
    import_statements: list[str] = Field(
        default_factory=list, description="List of import statements required for the process logic"
    )
    arguments: list[NeuProcessLogicArgument] = Field(
        default_factory=list, description="List of arguments for the process logic"
    )
    install_commands: str = Field(default='', description="Custom install commands for the process logic (semicolon & space separated)")
    output_entities: dict[str, str] = Field(
        default_factory=dict, description="Dictionary of output entities generated by the process logic (only for Python)"
    )
    has_metrics: bool = Field(
        default=False, description="Indicates if a 'metrics' dictionary is available in the code (only for Python)"
    )
    
    def __str__(self) -> str:
        """Return a human-readable string representation of the NeuProcessLogic."""
        return f"NeuProcessLogic(name='{self.about.name}', language={self.language}, kind={self.kind})"
    
    def __repr__(self) -> str:
        """Return a detailed string representation of the NeuProcessLogic."""
        code_preview = self.code[:50] + '...' if len(self.code) > 50 else self.code
        args = [arg.name for arg in self.arguments]
        imports = len(self.import_statements)
        
        return f"NeuProcessLogic(name='{self.about.name}', "\
               f"language={self.language}, kind={self.kind}, "\
               f"arguments={args}, imports={imports}, "\
               f"code='{code_preview}')"


    @field_validator("arguments")
    def validate_arguments(cls, v, info):
        # Get the kind from the validation info data
        kind = info.data.get("kind", NeuProcessKind.FILE)
        
        # Set default arguments if empty list, based on processing kind
        if not v:
            if kind == NeuProcessKind.BULK:
                # Bulk processing doesn't require specific arguments by default
                # The user's function should handle dataset access directly
                v = []
            else:
                # File-level processing requires input_filepath argument
                v = [NeuProcessLogicArgument(**arg) for arg in DEFAULT_ARGS_DICT]
        return v
        
    @field_validator("output_entities")
    def validate_output_entities(cls, v):
        if not v:
            return v
            
        # Check 1: All values must be strings (no nesting)
        for key, value in v.items():
            if not isinstance(value, str):
                raise ValueError(f"Value for key '{key}' must be a string, got {type(value).__name__}")
        
        # Check 2: All keys must be from the allowed set
        for key in v:
            if key not in ALLOWED_PYBIDS_ENTITY_KEYS:
                allowed_keys_str = ", ".join(f"'{k}'" for k in ALLOWED_PYBIDS_ENTITY_KEYS)
                raise ValueError(f"Invalid key '{key}'. Allowed keys are: {allowed_keys_str}")
                
        return v